language: python
python: "2.7"
install:
    - "npm install"
    - "npm install bower"
    - "bower install"
    - "pip install -r requirements.txt"
    - "./manage.py migrate"
script:
    - "npm run-script mocha"
    - "./manage.py test"
